### ISSUE TITLE
Link do Design no figma não está funcionando

### ISSUE THREAD

**Issue by princevasconcelos** [FotonTech/join#4]
Aqui tá dando 404.. pode ver se o link tá mesmo com problema ou é só aqui?

[Printscreen](https://imgur.com/XutwW6U)

**Comment by NomanGul** [comment]
Fixed link [here](https://dribbble.com/shots/3343472-Book-App-FREE-Sketch-Principle-File) :smiley: 

@jaburcodes Plz close this issue :+1:

**Comment by socksrust** [comment]
@NomanGul this is a drribble one, we need a figma public link, feel free to send a pr

**Comment by NomanGul** [comment]
@jaburcodes PR already sent by @johnzballad :smiley:

**Comment by jgcmarins** [comment]
Thanks
